# Generated by Django 4.2.3 on 2023-07-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemplateConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Site Name", max_length=50)),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
    ]
